10.0 migration
Vauxoo/account-payment pull request #3
Opened 2016-12-01 18:02 UTC by osvalr

2016-12-02 19:11 UTC, osvalr commented
@nhomar this is ready for review

2016-12-02 20:36 UTC, moylop260 commented
Could you explain a little more why this REM is need https://github.com/Vauxoo/account-payment/pull/3/commits/9c4e3bf8011775814f860842369d3c4e6eaaa731?

2016-12-02 21:55 UTC, osvalr commented
@moylop260 sure, I just updated the description, and the main reason is that they do not exists on newest version of odoo.

2016-12-02 22:26 UTC, moylop260 approved these changes

2016-12-02 22:41 UTC, nhomar commented
Can you check if this was not done already in oca/account-payment? if yes please check if it is ok if not please make a proper PR there also.

Regards.

2016-12-02 23:05 UTC, osvalr commented
@nhomar @moylop260 res_currency_print_on_check does not exists yet for 10.0, I've created a [task](https://www.vauxoo.com/web?db=vauxoo#id=6475&view_type=form&model=project.task&menu_id=136&action=138) to get it done later, can we proceed to merge this is there is not any other comments?

2016-12-03 01:25 UTC, nhomar requested changes

2016-12-03 01:25 UTC, nhomar commented on .travis.yml
> +  - TESTS="1" ODOO_REPO="vauxoo/odoo"
you do not need to change this to vauxoo/odoo only the main app repository is the one there.

2016-12-03 01:59 UTC, osvalr commented on .travis.yml
> +  - TESTS="1" ODOO_REPO="vauxoo/odoo"
now i get it

2016-12-03 02:39 UTC, merged